[package]
authors = [ "The syscall.rs Project Developers" ]
description = "Raw system calls"
documentation = "https://docs.rs/sc"
license = "MIT/Apache-2.0"
name = "sc"
readme = "README.md"
repository = "https://github.com/japaric/syscall.rs"
version = "0.1.0"
